### ISSUE TITLE
Support commitlint 18

### ISSUE THREAD

**Issue by wagoid** [vidavidorra/commitlint-plugin-function-rules#213]
Hi there! Could you add support for commitlint v18 in peer dependencies?

**Comment by jdbruijn** [comment]
Of course, will add it in a bit. I'll also figure out why Renovate didn't create a PR for that yet 😓

**Comment by jdbruijn** [comment]
The latter was due to requiring a non-existing status check and is now fixed.

Thanks for the reminder BTW, I should have added v18 support weeks ago.
